## Template script for creating new UIFlow pages via right-click menu.
## This is a placeholder — the actual content is generated by the plugin.
extends UIFlowPage

func _on_enter(_data: Dictionary = {}) -> void:
	pass

func _on_exit() -> void:
	pass

func _on_pause() -> void:
	pass

func _on_resume() -> void:
	pass
