## Template script for creating new UIFlow pages via right-click menu.
## This is a placeholder — the actual content is generated by the plugin.
extends UIFlowPage

func _on_created(_data: Variant = null) -> void:
	pass

func _on_opened(_data: Variant = null) -> void:
	pass

func _on_hidden() -> void:
	pass

func _on_shown() -> void:
	pass

func _on_closed() -> void:
	pass

func _on_destroyed() -> void:
	pass
